stages:
    - build
    - validate
variables:
  DOCKER_TLS_CERTDIR: ""

build_tf_container:
    stage: build
    image: docker
    services:
        - docker
    script: 
        - docker build -t my-docker-image .
job:
    stage: validate
    image: my-docker-image
    script: terraform validate ./Terraform
