stages:
    - build
    - validate
    
build_tf_container:
    stage: build
    image: docker
    services:
        - docker:dind
    before_script:
        - docker login registry.gitlab.com -u mateusz.lewicki -p 9YS9pwVMNNdEkz2kmx71
    script: 
        - docker build -t registry.example.com/private/aws_poc/terraform .
        - docker push registry.example.com/private/aws_poc/terraform
job:
    stage: validate
    image: registry.example.com/private/aws_poc/terraform:latest
    script: terraform validate ./Terraform
