variables:
    BUILD_TF_IMG: 'true'
    BUILD_PACKER_IMG: 'true'
    VALIDATE_TF: 'true'
    BUILD_AMI: 'true'
    DEPLOY_TF: 'true'

stages:
    - build_img
    - build_ami
    - validate
    - deploy
    
build_tf_container:
    stage: build_img
    image: docker
    services:
        - docker:dind
    before_script:
        - cd ./Terraform
        - docker login registry.gitlab.com -u $K8S_SECRET_DOCKER_USER -p $K8S_SECRET_DOCKER_KEY
    script: 
        - docker build -t registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/terraform .
        - docker push registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/terraform
    only: 
        variables:
            - $BUILD_TF_IMG=='true'

build_packer_container:
    stage: build_img
    image: docker
    services:
        - docker:dind
    before_script:
        - cd ./Packer
        - docker login registry.gitlab.com -u $K8S_SECRET_DOCKER_USER -p $K8S_SECRET_DOCKER_KEY
    script: 
        - docker build -t registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/packer .
        - docker push registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/packer
    only: 
        variables:
            - $BUILD_PACKER_IMG=='true'

build_worker_image:
    stage: build_ami
    image: registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/packer:latest
    script: packer build ./Packer/worker_img.json
    only: 
        variables:
            - $BUILD_AMI=='true'   


build_provision_image:
    stage: build_ami
    image: registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/packer:latest
    script: packer build ./Packer/provision_img.json
    only: 
        variables:
            - $BUILD_AMI=='true' 

validate_terraform:
    stage: validate
    before_script:
        - cd ./Terraform
        - terraform init
    image: registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/terraform:latest
    script: 
        - terraform validate
    only: 
        variables:
            - $VALIDATE_TF=='true'

deploy_terraform:
    stage: deploy
    before_script:
        - cd ./Terraform
        - terraform init
    image: registry.gitlab.com/$K8S_SECRET_DOCKER_USER/aws_poc/terraform:latest
    script: 
        - terraform apply
    only: 
        variables:
            - $DEPLOY_TF=='true'          
