variables:
    BUILD_TF_IMG: 'false'
    BUILD_PACKER_IMG: 'false'
    VALIDATE_TF: 'false'
stages:
    - build_img
    - build_ami
    - validate
    
build_tf_container:
    stage: build_img
    image: docker
    services:
        - docker:dind
    before_script:
        - cd ./Terraform
        - docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_KEY
    script: 
        - docker build -t registry.gitlab.com/$DOCKER_USER/aws_poc/terraform .
        - docker push registry.gitlab.com/$DOCKER_USER/aws_poc/terraform
    only: 
        variables:
            - $BUILD_TF_IMG=='true'

build_packer_container:
    stage: build_img
    image: docker
    services:
        - docker:dind
    before_script:
        - cd ./Packer
        - docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_KEY
    script: 
        - docker build -t registry.gitlab.com/$DOCKER_USER/aws_poc/packer .
        - docker push registry.gitlab.com/$DOCKER_USER/aws_poc/packer
    only: 
        variables:
            - $BUILD_PACKER_IMG=='true'

build_worker_image:
    stage: build_ami
    image: registry.gitlab.com/$DOCKER_USER/aws_poc/packer
    script: packer build ./Packer/worker_img.json

build_provision_image:
    stage: build_ami
    image: registry.gitlab.com/$DOCKER_USER/aws_poc/packer
    script: packer build ./Packer/provision_img.json

validate_terraform:
    stage: validate
    before_script:
        - cd ./Terraform
        - terraform init
    image: registry.gitlab.com/$DOCKER_USER/aws_poc/terraform:latest
    script: 
        - terraform validate
    only: 
        variables:
            - $VALIDATE_TF=='true'
