---
- hosts: localhost
  connection: local
  vars:
      GO_PATH: "/usr/local/go/bin"
      APPS:
            vault:
                name: vault
                version: "1.3.0"
            consul:
                name: consul
                version: "1.6.2"
            nomad:
                name: nomad
                version: "0.10.1"
      NOMAD_VERSION: "0.10.1"
      CONSUL_VERSION: "1.6.2"
      VAULT_VERSION: "1.3.0"
  tasks:
      - name: install needed tools
        block:
            - name: install curl
              yum:
                  name: curl
                  state: latest
              become: yes

            - name: install unzip
              yum:
                  name: unzip
                  state: latest
              become: yes
              
            - name: download golang
              shell: curl --silent --remote-name https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
            
            - name: untar golang
              shell: tar -xzf go1.13.4.linux-amd64.tar.gz -C /usr/local/
              
            - name: update bashrc
              shell: echo "{{ ansible_env.PATH }}:{{GO_PATH}}" >> /etc/environment 
              become: yes

      - name: install & configure vault
        block:
            - name: download vault
              shell: curl --silent --remote-name https://releases.hashicorp.com/vault/{{VAULT_VERSION}}/vault_{{VAULT_VERSION}}_linux_amd64.zip
  
            - name: unzip vault
              shell: unzip vault_{{VAULT_VERSION}}_linux_amd64.zip
            
            - name: change owner & move to bin
              copy:
                  src: ./vault
                  dest: /usr/local/bin/vault
                  owner: root
                  group: root
              become: yes
            - name: make vault data dir
              file:
                  path: /opt/vault
                  state: directory
    
            - name: make vault service file 
              template:
                  src: vault.service.j2
                  dest: /etc/init.d/vault
                  mode: '0755'
              vars: 
                  type: "server"
              become: yes
    
            - name: make vault conf dir
              file:
                  path: /etc/vault.d
                  state: directory
                  mode: '0700'
    
            - name: make vault config file 
              template:
                  src: vault.hcl.j2
                  dest: /etc/vault.d/vault.hcl
                  mode: '0755'
              become: yes
    
            - name: enable & start vault
              service:
                  name: vault
                  
                  enabled: yes
              become: yes
      - name: install & configure consul
        block:
            - name: download consul
              shell: curl --silent --remote-name https://releases.hashicorp.com/consul/{{CONSUL_VERSION}}/consul_{{CONSUL_VERSION}}_linux_amd64.zip

            - name: unzip consul
              shell: unzip consul_{{CONSUL_VERSION}}_linux_amd64.zip
        
            - name: change owner & move to bin
              copy:
                  src: ./consul
                  dest: /usr/local/bin/consul
                  owner: root
                  group: root
              become: yes
            - name: make consul data dir
              file:
                  path: /opt/consul
                  state: directory

            - name: make consul service file 
              template:
                  src: consul.service.j2
                  dest: /etc/init.d/consul
                  mode: '0755'
              vars: 
                  type: "server"
              become: yes

            - name: make consul conf dir
              file:
                  path: /etc/consul.d
                  state: directory
                  mode: '0700'

            - name: make consul config file 
              template:
                  src: consul.hcl.j2
                  dest: /etc/consul.d/consul.hcl
                  mode: '0755'
              become: yes
              vars: 
                  type: "server"

            - name: enable & start consul
              service:
                  name: consul
                  
                  enabled: yes
              become: yes
      - name: install & configure fabio
        block:
            - name: build fabio by Golang
              shell: go get github.com/fabiolb/fabio
              environment:
                  PATH: "{{ ansible_env.PATH }}:{{GO_PATH}}"
            - name: change owner & move to bin
              copy:
                  src: ./go/bin/fabio
                  dest: /usr/local/bin/fabio
                  owner: root
                  group: root
              become: yes
            - name: make fabio service file 
              template:
                  src: fabio.service.j2
                  dest: /etc/init.d/fabio
                  mode: '0755'
            - name: enable & start consul
              service:
                  name: fabio
                  
                  enabled: yes
              become: yes
      - name: install & configure nomad
        block:
            - name: download nomad
              shell: curl --silent --remote-name https://releases.hashicorp.com/nomad/{{NOMAD_VERSION}}/nomad_{{NOMAD_VERSION}}_linux_amd64.zip

            - name: unzip nomad
              shell: unzip nomad_{{NOMAD_VERSION}}_linux_amd64.zip
        
            - name: change owner & move to bin
              copy:
                  src: ./nomad
                  dest: /usr/local/bin/nomad
                  owner: root
                  group: root
              become: yes
        
            - name: make nomad data dir
              file:
                  path: /opt/nomad
                  state: directory

            - name: make nomad service file 
              template:
                  src: nomad.service.j2
                  dest: /etc/init.d/nomad
                  mode: '0755'
              vars: 
                  type: "server"
              become: yes

            - name: make nomad conf dir
              file:
                  path: /etc/nomad.d
                  state: directory
                  mode: '0700'

            - name: make nomad config file 
              template:
                  src: nomad.hcl.j2
                  dest: /etc/nomad.d/nomad.hcl
                  mode: '0755'
              become: yes

            - name: enable & start nomad
              service:
                  name: nomad
                  
                  enabled: yes
              become: yes
