---
- hosts: all
  vars:
      NOMAD_VERSION : "0.10.1"
      CONSUL_VERSION: "1.6.2"
      type: "client"
  tasks:
      - name: install curl
        yum:
            name: curl
            state: latest
        become: yes
      - name: install unzip
        yum:
            name: unzip
            state: latest
        become: yes
      - name: install & configure consul
        block:
            - name: download consul
              shell: curl --silent --remote-name https://releases.hashicorp.com/consul/{{CONSUL_VERSION}}/consul_{{CONSUL_VERSION}}_linux_amd64.zip
            - name: unzip consul
              shell: unzip consul_{{CONSUL_VERSION}}_linux_amd64.zip
        
            - name: change owner & move to bin
              copy:
                  src: ./consul
                  dest: /usr/local/bin/consul
                  owner: root
                  group: root
              become: yes
            - name: make consul data dir
              file:
                  path: /opt/consul
                  state: directory
            - name: make consul service file 
              template:
                  src: consul.service.j2
                  dest: /usr/lib/systemd/system/consul.service
                  mode: '755'
              become: yes
            - name: make consul conf dir
              file:
                  path: /etc/consul.d
                  state: directory
                  mode: '0700'
            - name: make consul config file 
              template:
                  src: consul.hcl.j2
                  dest: /etc/consul.d/consul.hcl
              become: yes
      - name: download nomad
        shell: curl --silent --remote-name https://releases.hashicorp.com/nomad/{{NOMAD_VERSION}}/nomad_{  {NOMAD_VERSION}}_linux_amd64.zip
      - name: unzip nomad
        shell: unzip nomad_{{NOMAD_VERSION}}_linux_amd64.zip
    
      - name: change owner & move to bin
        copy:
            src: ./nomad
            dest: /usr/local/bin/nomad
            owner: root
            group: root
        become: yes
    
      - name: make nomad data dir
        file:
            path: /opt/nomad
            state: directory
      - name: make nomad service file 
        template:
            src: nomad.service.j2
            dest: /usr/lib/systemd/system/nomad.service
            mode: '755'
        vars: 
            type: "client"
        become: yes
      - name: make nomad conf dir
        file:
            path: /etc/nomad.d
            state: directory
            mode: '0700'
      - name: make nomad config file 
        template:
            src: nomad.hcl.j2
            dest: /etc/nomad.d/nomad.hcl
        become: yes
      - name: make Shell directory
        file:
            path: Shell
            state: directory
      - name: make bootstrap script
        copy:
            src: ../Shell/worker_services.sh
            dest: Shell/worker_services.sh
            mode: '0755'
      - name: execute
        shell: Shell/worker_services.sh
        become: yes
  
